backend/app/views/admin.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    flash,
    Blueprint,
)
import plotly.express as px
import plotly.io as pio
from app.models import Service, Role, ProfessionalDetails
from app.utils import role_required
from app import db
from app.controllers import (
    search_professional,
    search_user,
    search_service,
    search_service_requests,
    create_service,
    deactivate_service,
    activate_professional,
)

admin_view_bp = Blueprint("admin", __name__, url_prefix="/admin")


@admin_view_bp.route("/home")
@role_required("admin")
def home():
    return render_template(
        "admin/home.html",
        services=search_service(with_deactivated=True),
        professionals=search_professional(with_deactivated=True),
        service_requests=search_service_requests(),
    )


@admin_view_bp.route("/add_service", methods=["GET", "POST"])
@role_required("admin")
def add_service():
    if request.method == "POST":
        try:
            create_service(request.form.to_dict())
            flash("Service added successfully", "success")
        except Exception as e:
            from traceback import print_exc

            print_exc()
            flash(f"Error in adding service: {str(e)}", "danger")
        return redirect(url_for("admin.home"))
    elif request.method == "GET":
        return render_template("admin/add_service.html")


@admin_view_bp.route("/approve_professional/<int:id>")
@role_required("admin")
def approve_professional(id):
    stat, msg = activate_professional(id)
    color = "success" if stat else "danger"
    flash(msg, color)
    return redirect(request.referrer or url_for("admin.home"))


@admin_view_bp.route("/block_professional/<int:id>")
@role_required("admin")
def block_professional(id):
    professional = ProfessionalDetails.query.get(id)
    professional.deactivate()
    flash("Professional blocked", "success")
    return redirect(request.referrer or url_for("admin.home"))


@admin_view_bp.route("/view_professional/<int:id>")
@role_required("admin")
def view_professional(id):
    professional = search_professional(with_deactivated=True, id=id)
    return render_template("admin/view_professional.html", professional=professional)


@admin_view_bp.route("/activate_user/<int:id>")
@role_required("admin")
def activate_user(id):
    user = search_user(with_deactivated=True, id=id)
    user.activate()
    flash("User activated successfully", "success")
    return redirect(request.referrer or url_for("admin.home"))


@admin_view_bp.route("/deactivate_user/<int:id>")
@role_required("admin")
def deactivate_user(id):
    user = search_user(id=id)
    user.deactivate()
    flash("User deactivated successfully", "success")
    return redirect(request.referrer or url_for("admin.home"))


@admin_view_bp.route("/edit_service/<int:id>", methods=["GET", "POST"])
@role_required("admin")
def edit_service(id):
    service = search_service(with_deactivated=True, id=id)
    if request.method == "POST":
        new_name = request.form.get("service_name")
        new_desc = request.form.get("service_description")
        new_base_price = request.form.get("base_price")
        if new_name != service.name:
            service.name = new_name
        if new_desc != service.description:
            service.description = new_desc
        if new_base_price != service.base_price:
            service.base_price = new_base_price

        db.session.commit()
        flash("Service updated successfully", "success")
        return redirect(url_for("admin.home"))
    elif request.method == "GET":
        return render_template("admin/add_service.html", service=service)


@admin_view_bp.route("/deactivate_service/<int:id>", methods=["POST"])
@role_required("admin")
def deactivate_service_view(id):
    try:
        deactivate_service(id)
        flash("Service deactivated successfully", "success")
    except Exception as e:
        print(e)
        flash(f"Error in deactivating service", "danger")
        raise e
    return redirect(url_for("admin.home"))


@admin_view_bp.route("/activate_service/<int:id>", methods=["POST"])
@role_required("admin")
def activate_service(id):
    print("Activating service")
    service = search_service(with_deactivated=True, id=id)
    service.activate()
    flash("Service activated successfully", "success")
    return redirect(url_for("admin.home"))


@admin_view_bp.route("/search", methods=["GET", "POST"])
@role_required("admin")
def search():
    if request.method == "POST":
        search_by = request.form.get("search_by")
        search_query = request.form.get("search_query")
        services, professionals, users, service_requests = [], [], [], []
        if search_by == "service":
            services = search_service(
                with_deactivated=True,
                name__like=search_query,
                description__like=search_query,
            )

        elif search_by == "professional":
            if search_query.isdigit():
                professionals = search_professional(
                    with_deactivated=True,
                    phone__like=search_query,
                    pincode__like=search_query,
                )
            else:
                professionals = search_professional(
                    with_deactivated=True,
                    username__like=search_query,
                    business_name__like=search_query,
                    description__like=search_query,
                    full_name__like=search_query,
                    address__like=search_query,
                )

        elif search_by == "customer":
            if search_query.isdigit():
                users = search_user(
                    with_deactivated=True,
                    phone__like=search_query,
                    pincode__like=search_query,
                )
            else:
                users = search_user(
                    with_deactivated=True,
                    username__like=search_query,
                    full_name__like=search_query,
                )
            admin_role = Role.query.filter_by(name="admin").first()
            users = [user for user in users if admin_role not in user.roles]
        elif search_by == "service_request":
            service_requests = []
            service_requests += (
                search_service_requests(remarks__like=search_query) or []
            )
            service_requests += (
                search_service_requests(
                    by="customer",
                    address__like=search_query,
                    full_name__like=search_query,
                    username__like=search_query,
                    phone__like=search_query,
                    pincode__like=search_query,
                )
                or []
            )
            service_requests += (
                search_service_requests(
                    by="professional",
                    business_name__like=search_query,
                    description__like=search_query,
                )
                or []
            )

        else:
            flash("Invalid search criteria", "danger")
            return redirect(url_for("admin.search"))
        if (
            sum([len(services), len(professionals), len(users)], len(service_requests))
            == 0
        ):
            flash("No results found", "warning")
            return redirect(url_for("admin.search"))
        return render_template(
            "admin/search.html",
            services=services,
            professionals=professionals,
            users=users,
            service_requests=service_requests,
        )
    return render_template("admin/search.html")


@admin_view_bp.route("/summary")
@role_required("admin")
def summary():
    # get all the customer ratings
    customer_ratings = {i: 0 for i in range(6)}
    all_service_requests = search_service_requests()
    issues_count = 0
    for service_request in all_service_requests:
        if service_request.rating:
            customer_ratings[service_request.rating] += 1
        else:
            customer_ratings[0] += 1
        if service_request.cust_issue_raised or service_request.prof_issue_raised:
            issues_count += 1
    # drop the 0 rating
    customer_ratings.pop(0)
    rating_fig = px.bar(
        x=list(customer_ratings.keys()),
        y=list(customer_ratings.values()),
        labels={"x": "Rating", "y": "Count"},
    )

    # get the status of all service requests and plot a pie chart
    status_count = {}
    for service_request in all_service_requests:
        if service_request.status not in status_count:
            status_count[service_request.status] = 1
        else:
            status_count[service_request.status] += 1
    status_fig = px.pie(
        values=list(status_count.values()),
        names=list(status_count.keys()),
    )

    # get html of the plots
    rating_plot_html = pio.to_html(rating_fig, full_html=False)
    status_plot_html = pio.to_html(status_fig, full_html=False)
    return render_template(
        "admin/summary.html",
        rating_plot_html=rating_plot_html,
        status_plot_html=status_plot_html,
        issues_count=issues_count,
    )

backend/app/views/public.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    flash,
    session,
    Blueprint,
    send_from_directory,
    current_app as app,
)
from flask_login import login_user, logout_user, login_required, current_user
import os
from app import login_manager
from app.models import User
from app.controllers import (
    create_customer,
    create_professional,
    search_service,
)
from app.forms import LoginForm
from app.utils.constants import AllowableRoles


public_view_bp = Blueprint("public", __name__, url_prefix="/")


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# Home route
@public_view_bp.route("/")
def home():
    return render_template("home.html")


# Login route
@public_view_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    print("Request Method:", request.method)  # Print the request method
    print("Form Data:", form.data)
    if form.validate_on_submit():
        messages = []
        username = form.username.data
        password = form.password.data
        chosen_role = form.role.data

        user = User.query.filter_by(username=username).first()
        print("User:", user)
        if not user:
            flash("User not found", "danger")
            return redirect(url_for("public.login"))
        elif not user.check_password(password):
            flash("Incorrect password", "danger")
            return redirect(url_for("public.login"))
        elif user.is_deactivated:
            flash("User is blocked, contact admin", "danger")
            return redirect(url_for("public.login"))
        elif chosen_role not in [role.name for role in user.roles]:
            flash("You are not authorized to access this role", "danger")
            return redirect(url_for("public.login"))
        else:
            # Successful login
            login_user(user)
            print("User logged in")
            session["role"] = chosen_role
            flash("Login successful", "success")
            return redirect(url_for(f"{chosen_role}.home"))

    return render_template("login.html", form=form)


# Logout route
@public_view_bp.route("/logout")
@login_required
def logout():
    logout_user()
    session.pop("role", None)
    flash("You have been logged out.", "info")
    return redirect(url_for("public.home"))


@public_view_bp.route("/about")
def about():
    return render_template("about.html")


@public_view_bp.route("/register/<role>", methods=["GET", "POST"])
def register(role):
    if role not in [AllowableRoles.CUSTOMER, AllowableRoles.PROFESSIONAL]:
        flash(f"Invalid role: {role}", "danger")
        return redirect(url_for("public.register", role=AllowableRoles.CUSTOMER))
    messages = []
    if request.method == "POST":
        print("Registering")
        username = request.form.get("username")
        password = request.form.get("password")
        cpassword = request.form.get("cpassword")
        if not username:
            messages.append("Username is required")
        if not password:
            messages.append("Password is required")
        if not cpassword:
            messages.append("Confirm password is required")
        if password and cpassword and password != cpassword:
            messages.append("Passwords do not match")
        new_user = None
        data = request.form.to_dict()
        for key in ["profile_pic", "experience_doc"]:
            file = request.files.get(key)
            if file:
                data[key] = file
        if role == AllowableRoles.PROFESSIONAL:
            new_user = create_professional(data)
        elif role == AllowableRoles.CUSTOMER:
            new_user = create_customer(data)
        if new_user:
            flash("User created successfully", "success")
            return redirect(url_for("public.login"))
        else:
            flash("User creation failed", "danger")
            return redirect(url_for("public.register", role=role))

    elif request.method == "GET":
        if role == AllowableRoles.PROFESSIONAL:
            services = search_service()
            return render_template(
                "register.html", role=role, available_services=services
            )
        return render_template("register.html", role=role)


@public_view_bp.route("/uploads/images/<filename>")
@login_required
def uploaded_image(filename):
    return send_from_directory(
        os.path.join(app.config["IMAGE_UPLOAD_FOLDER"]),
        filename,
    )


@public_view_bp.route("/uploads/files/<filename>")
@login_required
def uploaded_file(filename):
    return send_from_directory(
        os.path.join(app.config["FILE_UPLOAD_FOLDER"]),
        filename,
    )

backend/app/templates/components/base_registration.html
<!-- Username -->
<div class="form-group mb-3">
    <label for="username" class="form-label">Username</label>
    <input name="username" class="form-control" type="email" id="username" placeholder="user@example.com" required>
</div>
<!-- Full Name -->
<div class="form-group mb-3">
    <label for="full_name" class="form-label">Full Name</label>
    <input name="full_name" class="form-control" type="text" id="full_name" placeholder="User" required>
</div>
<!-- Address -->
<div class="form-group mb-3">
    <label for="address" class="form-label">Address</label>
    <textarea name="address" class="form-control" id="address" placeholder="Enter your address" rows="4"
        required></textarea>
</div>
<!-- Phone Number and pin code -->
<div class="row mb-3">
    <div class="form-group col-6">
        <label for="phone" class="form-label">Phone Number</label>
        <input name="phone" class="form-control" type="text" id="phone" placeholder="+91xxxxxxxxxx" required>
    </div>
    <div class="form-group col-6">
        <label for="pincode" class="form-label">Pin Code</label>
        <input name="pincode" class="form-control" type="text" id="pincode" placeholder="xxxxxx" required>
    </div>
</div>
<!-- Password and Confirm password-->
<div class="row mb-3">
    <div class="form-group col-6">
        <label for="password" class="form-label">Password</label>
        <input name="password" class="form-control" type="password" id="password" required>
    </div>
    <div class="form-group col-6">
        <label for="cpassword" class="form-label">Confirm Password</label>
        <input name="cpassword" class="form-control" type="password" id="cpassword" required>
    </div>
</div>
<!-- upload profile pic -->
<div class="form-group mb-3">
    <label for="profile_pic" class="form-label">Profile Picture</label>
    <input name="profile_pic" class="form-control" type="file" id="profile_pic" accept="image/jpeg, image/png">
</div>

backend/app/templates/components/del_service_modal.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del_{{service.id}}">
    Deactivate
</button>

<!-- Modal -->
<div class="modal fade" id="del_{{service.id}}" tabindex="-1" aria-labelledby="del_{{service.id}}_label"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ url_for('admin.deactivate_service_view', id=service.id) }}" method="POST">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteServiceLabel">Deactivate {{ service.name }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete {{ service.name }}?
                    Please note that this action will deactivate all professionals associated with this service. And you
                    will have to activate them manually

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Deactivate</button>
                </div>
            </form>
        </div>
    </div>
</div>

backend/app/templates/components/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <!-- Brand on the left -->
        <!-- logo image -->
        {% if current_user.is_authenticated and session.get('role') in ['professional', 'customer'] %}
        <a class="navbar-brand" href="{{ url_for(session.get('role')+'.edit_profile') }}">
            <img src="{{ url_for('public.uploaded_image', filename=current_user.profile_pic) }}" alt="profile"
                width="28" height="28" class="rounded-circle">
            {{ current_user.full_name.capitalize() }}
        </a>
        {% else %}
        <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='images/logo.png') }}" alt="logo"
                width="28" height="28" class="rounded-circle">Household</a>
        {% endif %}
        <!-- <a class="navbar-brand" href="#">Household</a> -->

        <!-- Toggler button for mobile view -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navigation items pushed to the right using ms-auto -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for(session.get('role', 'public')+'.home')}}">Home</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for(session.get('role', 'public')+'.search')}}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for(session.get('role', 'public')+'.summary')}}">Summary</a>
                </li>
                {%else%}
                <li>
                    <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
                </li>
                {%endif%}
                {% if not current_user.is_authenticated %}
                <!-- dropdown register -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Register
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item"
                                href="{{ url_for('public.register', role='customer') }}">Customer</a></li>
                        <li><a class="dropdown-item"
                                href="{{ url_for('public.register', role='professional') }}">Professional</a>
                        </li>
                    </ul>
                </li>
                {%endif%}
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('public.logout') }}">Logout</a>
                    {%else%}
                    <a class="nav-link" href="{{ url_for('public.login') }}">Login</a>
                    {%endif%}
                </li>

            </ul>
        </div>
    </div>
</nav>

backend/app/templates/components/service_modal.html
<!-- Button trigger modal -->
{% if service %}
{% set id_name = 'edit_' + service.name.replace(' ', '') %}
{% set url = url_for('admin.edit_service', id=service.id) %}
{% else %}
{% set id_name = 'add-service' %}
{% set url = url_for('admin.add_service') %}
{% endif %}

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#{{ id_name }}">
    {% if service %}Edit{% else %}Add Service{% endif %}
</button>

<!-- Modal -->
<div class="modal fade" id="{{ id_name }}" tabindex="-1" aria-labelledby="{{ id_name + '_label' }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ url }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title fs-5" id="{{ id_name + '_label' }}">
                        {% if service %}Edit {{ service.name }}{% else %}Add Service{% endif %}
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="form-group mb-3">
                        <label for="service_name" class="form-label">Service Name</label>
                        <input name="service_name" class="form-control" type="text" id="service_name"
                            placeholder="Service Name" {% if service %}value="{{ service.name }}" {% endif %}>
                    </div>
                    <div class="form-group mb-3">
                        <label for="service_description" class="form-label">Service Description</label>
                        <textarea name="service_description" class="form-control" id="service_description"
                            placeholder="Service Description">{% if service %}{{ service.description }}{% endif %}</textarea>
                    </div>
                    <div class="form-group mb-3">
                        <label for="base_price" class="form-label">Base Price</label>
                        <input name="base_price" class="form-control" type="number" id="base_price"
                            placeholder="Base Price" {% if service %}value="{{ service.base_price }}" {% endif %}>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

backend/app/templates/components/view_professional_modal.html
<!-- Button to trigger modal -->
{% if modal_trigger_type == 'link' %}
<a href="#" class="text-primary text-decoration-none shadow-sm hover-link" data-bs-toggle="modal"
    data-bs-target="#professionalDetailsModal-{{ professional.id }}">
    {{ professional.business_name }}
</a>
{% else %}
<button type="button" class="btn btn-primary" data-bs-toggle="modal"
    data-bs-target="#professionalDetailsModal-{{ professional.id }}">
    View
</button>
{% endif %}


<!-- Modal -->
<div class="modal fade" id="professionalDetailsModal-{{ professional.id }}" tabindex="-1"
    aria-labelledby="professionalDetailsModalLabel-{{ professional.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="professionalDetailsModalLabel-{{ professional.id }}">Professional Details
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Professional details content -->
                <div class="container">
                    <div class="row mb-3">
                        <div class="col-md-4">
                            <img src="{{ url_for('public.uploaded_image', filename= professional.user.profile_pic) }}"
                                class="img-fluid" alt="Profile Picture" max-height="200">
                        </div>
                        <div class="col-md-8">
                            <h3>{{ professional.business_name }}</h3>
                            <p><strong>Name:</strong> {{ professional.user.full_name }}</p>
                            <p><strong>Username:</strong> {{ professional.user.username }}</p>
                            <p><strong>Address:</strong> {{ professional.user.address }}</p>
                            <p><strong>Pincode:</strong> {{ professional.user.pincode }}</p>
                            <p><strong>Phone:</strong> {{ professional.user.phone }}</p>
                            <p><strong>Average Rating:</strong> {{ professional.avg_rating }}</p>
                        </div>
                    </div>

                    <hr>

                    <!-- Professional service details -->
                    <h4>Service Details</h4>
                    <p><strong>Service:</strong> {{ professional.service.name }}</p>
                    <p><strong>Description:</strong> {{ professional.description }}</p>
                    <p><strong>Experience (years):</strong> {{ professional.experience }}</p>
                    <p><strong>Document:</strong> <a
                            href="{{ url_for('public.uploaded_file', filename=professional.document) }}"
                            target="_blank">{{
                            professional.document }}</a></p>
                    <embed src="{{ url_for('public.uploaded_file', filename=professional.document) }}"
                        type="application/pdf" width="100%" height="600px" />
                    <p><strong>Total Price:</strong> ₹{{professional.service.base_price + professional.extra_price }}
                    <p>(<i>Base Price:</i> ₹{{ professional.service.base_price }};
                        <i>Premium:</i> ₹{{ professional.extra_price }})
                    </p>
                    </p>
                    {% if session['role'] == 'admin' %}
                    <p style="display: inline;"><strong>Status:</strong>
                    <div class="badge {% if professional.is_deactivated %}bg-danger{% else %}bg-success{% endif %}">
                        {{ 'Inactive' if professional.is_deactivated else 'Active' }}

                    </div>
                    </p>
                    {% if professional.is_deactivated == True %}
                    <a href="{{ url_for('admin.approve_professional', id=professional.id) }}"
                        class="btn btn-success">Activate</a>
                    {% else %}
                    <a href="{{ url_for('admin.block_professional', id=professional.id) }}"
                        class="btn btn-danger">deactivate</a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

backend/app/templates/components/view_user_modal.html
<!-- Button to trigger modal -->
{% if modal_trigger_type == 'link' %}
<a href="#" class="text-primary text-decoration-none shadow-sm hover-link" data-bs-toggle="modal"
    data-bs-target="#userDetailsModal-{{ user.id }}">
    {{ user.full_name }}
</a>
{% else %}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#userDetailsModal-{{ user.id }}">
    View
</button>
{% endif %}


<!-- Modal -->
<div class=" modal fade" id="userDetailsModal-{{ user.id }}" tabindex="-1"
    aria-labelledby="userDetailsModalLabel-{{ user.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userDetailsModalLabel-{{ user.id }}">User Details
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- user details content -->
                <div class="container">
                    <div class="row mb-3">
                        <div class="col-md-4">
                            <img src="{{ url_for('public.uploaded_image', filename= user.profile_pic) }}"
                                class="img-fluid" alt="Profile Picture" max-height="200">
                        </div>
                        <div class="col-md-8">
                            <h3>{{ user.full_name }}</h3>
                            <p><strong>Username:</strong> {{ user.username }}</p>
                            <p><strong>Address:</strong> {{ user.address }}</p>
                            <p><strong>Pincode:</strong> {{ user.pincode }}</p>
                            <p><strong>Phone:</strong> {{ user.phone }}</p>
                            {% if session['role'] == 'admin' %}
                            {% if user.is_deactivated %}
                            <a href="{{ url_for('admin.activate_user', id=user.id) }}"
                                class="btn btn-success">Activate</a>
                            {% else %}
                            <a href="{{ url_for('admin.deactivate_user', id=user.id) }}"
                                class="btn btn-danger">Deactivate</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>